- fakesnow/fakes.py
- tests/test_fakes.py
I ran into an issue when using fakesnow with parameterized SQL queries. I was seeing:
```
def description(self) -> list[ResultMetadata]:
with self._duck_conn.cursor() as cur:
assert self._conn.database, "Not implemented when database is None"
assert self._conn.schema, "Not implemented when database is None"
cur.execute(f"SET SCHEMA = '{self._conn.database}.{self._conn.schema}'")
>           cur.execute(f"DESCRIBE {self._last_sql}")
E           duckdb.InvalidInputException: Invalid Input Error: Prepared statement needs 1 parameters, 0 given
```
The issue was that DESCRIBE was assuming _last_sql parameters were already filled in, but this isn't the case for server-side parameter binding. See:
https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-example#qmark-or-num …
> fix: describe to work with parameterized SQL queries

- fakesnow/info_schema.py
- tests/test_fakes.py
- tests/test_info_schema.py
In the 2nd commit, I relocate all the information_schema-related tests into a single file (again, somewhat opinionated decision, but infinitely adding tests to test_fakes seemed like perhaps not ideal, as the info schema stuff is only likely to get larger).
> feat: implement information_schema.views

- fakesnow/__init__.py
- fakesnow/fakes.py
- fakesnow/info_schema.py
- fakesnow/transforms.py
- pyproject.toml
- tests/conftest.py
- tests/test_fakes.py
- tests/test_sqlalchemy.py
As I mentioned before, thus far I've just been trying to get increasing numbers of existing features working with fakesnow.
The e2e feature attempting to be fixed here is `CREATE VIEW`, but there's more going on than just support for the statement. As such, I've tried to implement tests that address each added bit of functionality directly.
* Adjust the output of `CREATE VIEW` akin to what you're already doing for `CREATE TABLE`
* Begin support of table reflection
* Support `SHOW PRIMARY KEYS` (called internally to sqlalchemy), at least to a minimal extent. It now syntatically works and does what would seem to be correct (except that I dont see an equivalent to "constraint_name" in duckdb). Seems to work, but without it working e2e it's hard to be sure
* Added an `xfail` test for table …
> feat: SHOW PRIMARY KEYS + description for CREATE VIEW + fix information_schema.columns to work with sqlalchemy

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_transforms.py
Seems like already handled by `sqlglot`, removing transformation won't break any tests;
```python
q1 = """SELECT PARSE_JSON('{"k1": "v1"}')"""
parse_one(q1, dialect="snowflake").sql(dialect="duckdb")
q2 = """SELECT PARSE_JSON(col)"""
parse_one(q2, dialect="snowflake").sql(dialect="duckdb")
```
```python
Select(
expressions=[
ParseJSON(
this=Literal(this={"k1": "v1"}, is_string=True))])
Select(
expressions=[
ParseJSON(
this=Column(
this=Identifier(this=col, quoted=False)))])
```
----
Left `test_parse_json` as is without any transformation in case of any `sqlglot` changes. There're other tests those cover it in fakes tests though deleting kinda makes sense.
------------------
* Python: 3.9.18
* sqlglot: 21.2.1
> refactor: remove parse_json as handled by sqlglot

- fakesnow/fakes.py
- tests/test_fakes.py
`_insert_df` needs to quote the column names when inserting, otherwise fails for table where column names need quoting
> fix: write_pandas quotes columns when inserting dataframe

- fakesnow/transforms.py
- pyproject.toml
- tests/test_transforms.py
* nested json accesses combined into a single path;
```diff
--- old
+++ new
@@ -1 +1 @@
-col -> '$.K1' -> '$.K2'
+col -> '$.K1.K2'
```
* `TO_NUMBER(...)` parsed as `exp.ToNumber`, but AST is a little weird for Snowflake and it is not generated as `DECIMAL` in DuckDB but as `DOUBLE`;
https://github.com/tobymao/sqlglot/blob/2a3a5cdc/sqlglot/dialects/duckdb.py#L368-L368
https://github.com/tobymao/sqlglot/blob/2a3a5cdcffe39d42153b3e960a580d084a27c0eb/sqlglot/generator.py#L3315-L3326
```python
ToNumber(
this=Literal(this=100, is_string=True))
```
```python
ToNumber(
this=Literal(this=100, is_string=True),
format=Literal(this=10, is_string=False))
```
```python
ToNumber(
this=Literal(this=100, is_string=True),
format=Literal(this=10, is_string=False),
precision=Literal(this=2, is_string=False)) …
```
> chore(deps): bump sqlglot to 23.3.0

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
In Snowflake, to order elements in `ARRAY_AGG` aggregation one needs to provide `WITHIN GROUP (..)`;
* https://docs.snowflake.com/en/sql-reference/functions/array_agg#arguments
```
ARRAY_AGG(<expr>) WITHIN GROUP (<order-by-clause>)
```
In DuckDB, `LIST()/ARRAY_AGG()` requires expression to be passed ordered and does not support `WITHIN GROUP (...)`;
* https://duckdb.org/docs/sql/aggregates.html#order-by-clause-in-aggregate-functions
```
ARRAY_AGG( <expr> <order-by-clause> )
```
This transformer simply combines *aggreage* expression in `ARRAY_AGG` and *ordering* one in `WITHIN GROUP` in an *order* expression.
```sql
ARRAY_AGG(DISTINCT id) WITHIN GROUP (ORDER BY id)
```
```python
WithinGroup(
this=ArrayAgg(
this=Distinct(
expressions=[
Column(
this=Identifier(this=id, quoted=False))])), …
```
> feat: add ARRAY_AGG() WITHIN GROUP() support

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
We're using Snowflake `sha2` function in our project that uses `fakesnow` for testing (it's great, thank you!)
But duckdb does not have `sha2` function, instead it has a `sha256` function
`sha256(foo)` is the same as Snowflake `sha2('foo', 256)` (or you can omit the length arg and it defaults to 256) https://docs.snowflake.com/en/sql-reference/functions/sha2#arguments
So this PR adds a transform for these function calls
> feat: support sha2 and sha2_hex with digest size of 256

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
Adds transformation for `TRY_TO_DECIMAL` and friends, basically the same as `to_decimal` except returned node is `TryCast` instead of `Cast`.
Moved the actual node creation to another function to reuse it in both `*to_decimal` transformation, but not 100% sure with what I end up with. 
Keeping the same logic in both functions makes it more explicit and more isolated but prone to failures in a case that is not covered by tests, would like to hear what you think about it.
----------------
> [!NOTE]  
> I'm working on a wrapper dbt adapter so users can write unit tests and run locally. Thank you for this awesome project as it really sped things up and kept my focus solely on query transformations.
>
> I have a couple more transformation but not sure if all fits in the scope of the project as …
> feat: add TRY_TO_{DECIMAL,...}

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
Snowflake -again- seems to cast string literal in `DATEADD`  to `TIMESTAMP_LTZ` or `TIMESTAMP_NTZ` depending on `TIMESTAMP_TYPE_MAPPING` session parameter.
```sql
select
dateadd('day', 3, '2023-04-02') as c1, SYSTEM$TYPEOF(c1),
dateadd('week', 3, '2023-04-02') as c3, SYSTEM$TYPEOF(c3),
dateadd('month', 3, '2023-04-02') as c5, SYSTEM$TYPEOF(c5),
dateadd('year', 3, '2023-04-02') as c7, SYSTEM$TYPEOF(c7),
;
```
|              C1               |   SYSTEM$TYPEOF(C1)    |
|-------------------------------|------------------------|
| 2023-04-05 00:00:00.000 +0000 | TIMESTAMP_LTZ(9)[SB16] |
|              C3               |   SYSTEM$TYPEOF(C3)    |
|-------------------------------|------------------------|
| 2023-04-23 00:00:00.000 +0000 | TIMESTAMP_LTZ(9)[SB16] |
|              C5               | …
> feat: cast string literals to timestamp in dateadd

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
Basically the same as https://github.com/tekumara/fakesnow/pull/72 but for `DATEDIFF`. 
Same concerns of the `DATEADD` change applies here;
> But I'm a little bit concerned on TIMESTAMP as DuckDB is quite picky operations between TIMESTAMP and TIMESTAMP WITH TIMEZONE. Like; CURRENT_TIMESTAMP returns TIMESTAMP WITH TIMEZONE and DATE_DIFF expects either operands to be same typed. I saw that to_timestamp transformation casts to TIMESTAMP and went with it.
> feat: cast string literals to timestamp in datediff

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
Snowflake's [`DATEADD(<date_or_time_part>, <value>, <date_or_time_expr> )`](https://docs.snowflake.com/en/sql-reference/functions/dateadd) seems to return `DATE` if;
* `date_or_time_expr` is `DATE` typed.
* and `date_or_time_part` is either `DAY`, `WEEK`, `MONTH`, `YEAR`.
```sql
with
t1 as(
select '2023-03-01' as literal, '2023-03-01'::date as date_valued
)
select 
dateadd('day', 3, literal::DATE) as c1, SYSTEM$TYPEOF(c1),
dateadd('day', 3, date_valued) as c2, SYSTEM$TYPEOF(c2),
dateadd('week', 3, literal::DATE) as c3, SYSTEM$TYPEOF(c3),
dateadd('week', 3, date_valued) as c4, SYSTEM$TYPEOF(c4),
dateadd('month', 3, literal::DATE) as c5, SYSTEM$TYPEOF(c5),
dateadd('month', 3, date_valued) as c6, SYSTEM$TYPEOF(c6),
dateadd('year', 3, literal::DATE) as c7, SYSTEM$TYPEOF(c7),
dateadd('year', …
```
> feat: mimic dateadd with date + day/week/month/year

- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
sqlglot transforms Snowlake's `zeroifnull` to `case when .. is null ...` statement. In `object_construct`, removing every `NULL` expression generates an unexpected query;
```sql
-- snowflake
SELECT OBJECT_CONSTRUCT( 'k1', 'v1', 'k2', CASE WHEN ZEROIFNULL(col) + 1 >= 2 THEN 'v2' ELSE NULL END, 'k3', 'v3')
-- before
SELECT TO_JSON({'k1': 'v1', 'k2': , 'k3': 'v3'})
-- after
SELECT TO_JSON({'k1': 'v1', 'k2': CASE WHEN CASE WHEN col IS NULL THEN 0 ELSE col END + 1 >= 2 THEN 'v2' ELSE NULL END, 'k3': 'v3'})
--                                          |------zeroifnull(col)-----|
```
AFAIS `Struct` only contains `EQ` expressions on `object_construct`. Instead of removing every `NULL` we can just remove `NULL` keyed/valued `EQ` expressions.
> fix: remove only null key/values in object_construct

- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
Not sure if intentional but despite doc comment `Return raw unquoted string when casting json extraction to varchar`, `json_extract_cast_as_varchar` transforms all CASTs on JSON extraction to `VARCHAR`.
```sql
-- snowflake
select parse_json('{"fruit":"9000"}'):fruit::number
-- becomes in duckdb;
SELECT JSON('{"fruit":"9000"}') ->> '$.fruit'
```
> fix(json extraction): only return string when casting to varchar

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
Snowflake's [`TRIM`](https://docs.snowflake.com/en/sql-reference/functions/trim) accepts any type and returns VARCHAR, docs does not mentioned it but it seems to only works on VARCHAR/TEXT typed inputs and acts as a cast to VARCHAR for others.  DuckDB's `TRIM` only accepts VARCHAR. It seemed safe to me to cast input to VARCHAR to mimic similar behaviour.
```sql
select 
trim(5) as c_number, SYSTEM$TYPEOF(c_number),
trim(' str ') as c_varchar, SYSTEM$TYPEOF(c_varchar),
trim(to_variant({'k': 'v'})) as c_variant, SYSTEM$TYPEOF(c_variant)
;
```
| C_NUMBER | SYSTEM$TYPEOF(C_NUMBER) | C_VARCHAR | SYSTEM$TYPEOF(C_VARCHAR) | C_VARIANT | SYSTEM$TYPEOF(C_VARIANT) |
|----------|-------------------------|-----------|--------------------------|-----------|--------------------------|
|        5 | …
> feat: support trim with numeric and variant types

- fakesnow/transforms.py
- tests/test_fakes.py
I've encountered another precedence issue with json extract scalar this time;
```sql
select JSON('{"K1": "a", "K2": "b"}') as col, CASE WHEN COL ->> '$.K1' = 'a' AND COL ->> '$.K2' = 'b' THEN 'yes' END as r;
-- Error: Conversion Error: Failed to cast value to numerical: {"K1":"a","K2":"b"}
select JSON('{"K1": "a", "K2": "b"}') as col, CASE WHEN (COL ->> '$.K1') = 'a' AND (COL ->> '$.K2') = 'b' THEN 'yes' END as r;
-- ┌─────────────────────┬─────────┐
-- │         col         │    r    │
-- │        json         │ varchar │
-- ├─────────────────────┼─────────┤
-- │ {"K1":"a","K2":"b"} │ yes     │
-- └─────────────────────┴─────────┘
```
> fix: GET_PATH precedence for JSONExtractScalar

- fakesnow/fakes.py
- tests/test_fakes.py
- tests/test_sqlalchemy.py
fwiw, I'm attempting to use fakesnow to test alembic migrations of snowflake 😬.
You already have a test for `alter table`, but sqlalchemy (versus the raw cursor) always calls `.description` on the results of queries and it was hitting similar issues to issues you've already solved with e.g. `CREATE TABLE` etc.
I deviated from the pattern a little bit because `AlterTable` constructs returned `ALTERTABLE` as the `cmd`. It seemed somewhat unfortunate to compare exactly against that, but also seemed very likely that other ALTER statements would have the same generic output.
> fix: ALTER TABLE result output

- fakesnow/fakes.py
- fakesnow/transforms.py
- tests/test_fakes.py
When patching in a test specifying a db_path and attempting to create a database:
```
with fakesnow.patch(db_path="databases"):
cursor = snowflake.connector.connect().cursor()
cursor.execute(f"CREATE DATABASE TEST32cs3s3")
```
the following error is thrown
```
>           db_file = f"{db_path/db_name}.db" if db_path else ":memory:"
E           TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
This PR fixes the string interpolation.
Note that I expect there is a similar bug in [fakes.py#538](https://github.com/jazzarati/fakesnow/blob/14e6a41bdc133ebc86630467dcaf997c943dfd8a/fakesnow/fakes.py#L538) but I couldn't figure out how to trigger it via a test.
PS: Thanks for making this project
> fix: CREATE DATABASE when using db_path

- fakesnow/transforms.py
- tests/test_fakes.py
- tests/test_transforms.py
If a database already existed and we try to execute "CREATE DATABASE IF NOT EXISTS DB2" then it currently fails with error:
```
snowflake.connector.errors.ProgrammingError: 002043 (02000): Binder Error: Unique file handle conflict: Database "DB2" is already attached with path "...fakesnow-testl1jfag6s/DB2.db"
```
This commit adds support for this functionality by converting the statement to the [duckdb syntax of ATTACH IF NOT EXISTS](https://duckdb.org/docs/sql/statements/attach) when the exists clause is present.
Up to you if you want to keep the test in `test_fakes.py` or only use the one in `test_transforms.py`
> fix: Support IF NOT EXISTS in CREATE DATABASE statements

- fakesnow/fakes.py
- fakesnow/transforms.py
- fakesnow/variables.py
- tests/test_fakes.py
Implements the very basic usages of sql variables
```
SET var2 = 'blue';
SELECT * from table where color = $var2;                  Produces: SELECT * from table where color = 'blue';
UNSET var2;
```
as described in https://docs.snowflake.com/en/sql-reference/session-variables.
List of features supported and not supported by this PR:
> feat: Implements basic snowflake session variables via SET/UNSET

- fakesnow/transforms.py
- tests/test_info_schema.py
Previously there was a `NotImplemented` error when running a query to request the PKs of a table.
I added support for listing the PKs of a table.
> feat: SHOW PRIMARY KEYS for table

- fakesnow/variables.py
The existing logic to set a variable was being triggered by some other sql that includes the SET keyword.
I found this case when working on MERGE which has the statement WHEN MATCHED THEN SET ... This triggered the issue. 
Unfortunately we don't currently support MERGE and UPDATE TABLE SET ... statements don't seem to trigger this issue so I couldn't find an existing supported usecase to add a test so there are no new tests.
Once MERGE is built it will fail without this change so its a future test case that will cover us.
In this PR I also inverted the expression and fixed some bad variable naming that was confusing.
> fix: Only set variables for SetItem expressions

- fakesnow/info_schema.py
- tests/test_info_schema.py
I noticed this when trying to use snowflake-sqlalchemy to test view creation using fakesnow. It's actually sort of also a bug in snowflake-sqlalchemy, that it's hitting an untested code path and failing. but also, this column **should** have a type, and adding one avoids the latent bug in snowflake-sqlalchemy.
> fix: Ensure type column in information_schema views is not null

- fakesnow/fakes.py
- tests/test_connect.py
- tests/test_fakes.py
With snowflake, it's sometimes (particularly with alembic) convenient to connect with `schema='information_schema'`, so that all other schemas are required explicitly (since there's no public schema, and the weird way snowflake scoping works).
As-is without this PR, the duckdb `information_schema` is lowercased, and the auto-use-schema code in fakesnow would unconditionally `.upper()` the given schema, search for `INFORMATION_SCHEMA`, not find it, and then you'd get `This session does not have a current schema. Call 'USE SCHEMA'` when you wouldn't in real life.
It might perhaps be more ideal to somehow fully recreate the snowflake information_schema and replace it, because there **are** some differences with the duckdb version that i suspect will end up being irreconcilable, but it's not …
> fix: Allow connection with schema=information_schema

- fakesnow/variables.py
- tests/test_fakes.py
Identifiers containing dollar signs, though valid as per Snowflake documentation, were not supported.
This PR fixes the regexp identifying internal variables:
```
CREATE DATABASE ORG$INTERNAL;
fakesnow/cursor.py:170: in execute
raise e
fakesnow/cursor.py:148: in execute
command = self._inline_variables(command)
fakesnow/cursor.py:496: in _inline_variables
return self._conn.variables.inline_variables(sql)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <fakesnow.variables.Variables object at 0x11e4a2f10>, sql = 'CREATE DATABASE ORG$INTERNAL;'
def inline_variables(self, sql: str) -> str:
for name, value in self._variables.items():
sql = re.sub(rf"\${name}", value, sql, flags=re.IGNORECASE)
if …
```
> fix: support identifiers containing dollar signs

- fakesnow/server.py
- tests/test_server.py
This fixes the .NET connector throwing an error when attempting to connect as it expects a sessionInfo object on the data.
```
> dotnet run snowflake-test.cs
Unhandled exception. Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: Snowflake Internal Error: Unable to connect. Object reference not set to an instance of an object. SqlState: 08006, VendorCode: 270001, QueryId:
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Snowflake.Data.Core.SFSession.ProcessLoginResponse(LoginResponse authnResponse)
...
```
After this fix fakesnow works from C# and I'm able to successfully run queries.
I thought it was safer to put an empty object to make this connector work rather than populating its fields, but I'm happy to populate the database, …
> feat(server): basic sessionInfo login response

- fakesnow/server.py
- tests/conftest.py
- tests/test_server.py
using local storage (ie: LOCAL_FS) because remote storage (eg: S3) uses HTTPS which requires some sort of certificate
only supports default PUT params
> feat(server): support basic PUT

- fakesnow/cursor.py
- pyproject.toml
Pandas does not appear to be a direct transitive dependency of fakesnow (and you seem to have an `if TYPE_CHECKING` block specifically to lazy-import pandas already).
So this top-level import seems to either be a missing required dependency, or it needs to be inlined/otherwise made lazy.
I'd have made it try/catch at the top level, but that messes up typing typically.
Afaict this is the only direct use of `pd` in the file outside type hints.
> refactor: remove use of pandas

- fakesnow/macros.py
- fakesnow/transforms/transforms.py
- tests/test_timestamp.py
- tests/test_transforms.py
Snowflake `TO_TIMESTAMP` can accept a `scale` parameter that specifies time units of the number
For seconds, scale = 0
For milliseconds, scale = 3
For microseconds, scale = 6
For nanoseconds, scale = 9
I have adjusted both `_fs_to_timestamp` macro and the `to_timestamp` transformation to take `scale` into account.
Otherwise calls like `TO_TIMESTAMP(1752253006000, 3)` would create incorrect timestamp
> feat: support scale argument in to_timestamp function

- fakesnow/transforms/__init__.py
- fakesnow/transforms/ddl.py
- fakesnow/transforms/transforms.py
- tests/test_ddl.py
- tests/test_transforms.py
This PR refactors DDL transforms by moving the logic for handling ALTER TABLE strip CLUSTER BY operations into `ddl.py`. No functional changes were made; code was relocated for better organization and maintainability.
> refactor: Move ALTER TABLE strip CLUSTER BY transform method
